export const MOKC_RESPONSE_PINBANK_DOCS = {
   Data: {
      StatusContaDigital: "string",
      ListaDocumentosCadastrados: [
         {
            CodigoDocumento: 0,
            TipoDocumento: 0,
            DescricaoDocumento: "string",
            StatusDocumento: "APROVADO",
            TipoPessoa: "Fisica",
            NomeArquivo: "string",
            ArquivoBase64: "string",
            MotivoDevolucao: "string",
         }, {
            CodigoDocumento: 0,
            TipoDocumento: 0,
            DescricaoDocumento: "string",
            StatusDocumento: "APROVADO",
            TipoPessoa: "Fisica",
            NomeArquivo: "string",
            ArquivoBase64: "string",
            MotivoDevolucao: "string",
         }, {
            CodigoDocumento: 0,
            TipoDocumento: 0,
            DescricaoDocumento: "string",
            StatusDocumento: "APROVADO",
            TipoPessoa: "Fisica",
            NomeArquivo: "string",
            ArquivoBase64: "string",
            MotivoDevolucao: "string",
         }, {
            CodigoDocumento: 0,
            TipoDocumento: 0,
            DescricaoDocumento: "string",
            StatusDocumento: "APROVADO",
            TipoPessoa: "Fisica",
            NomeArquivo: "string",
            ArquivoBase64: "string",
            MotivoDevolucao: "string",
         }, {
            CodigoDocumento: 0,
            TipoDocumento: 0,
            DescricaoDocumento: "string",
            StatusDocumento: "APROVADO",
            TipoPessoa: "Fisica",
            NomeArquivo: "string",
            ArquivoBase64: "string",
            MotivoDevolucao: "string",
         },
      ],
   },
   ResultCode: 0,
   Message: "string",
   ValidationData: {
      ResultCode: 0,
      Message: "string",
      Errors: [
         {
            ErrorMessage: "string",
            FieldName: "string",
         },
      ],
   },
}