name: Gemini Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Code Review
        uses: actions/github-script@v7
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        with:
          script: |
            const { execSync } = require('child_process');
            
            const diff = execSync(`git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }}`, 
              { encoding: 'utf8' });
            
            if (!diff.trim()) return;
            
            const response = await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=' + process.env.GEMINI_API_KEY, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                contents: [{
                  parts: [{ text: `Revise este código e sugira melhorias:\n\n${diff.substring(0, 4000)}` }]
                }]
              })
            });

            const data = await response.json();
            const review = data.candidates[0].content.parts[0].text;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 **Code Review**\n\n${review}`
            });